### ISSUE TITLE
No terminal output

### ISSUE THREAD

**Issue by 70sh1** [dividebysandwich/LightningView#1]
Hello there. Interesting project.

I built it and tried it out. Unfortunately I noticed that there is no text output in my terminal. I looked into the code a bit and tried adding more `println!()` lines, but they just don't seem to work, which I find quite odd. The binary from releases behaves the same.

I'm not very familiar with Rust though. Any hints?

I'm running Windows 11 & Powershell 7.4.1 (cmd gives the same results).

**Comment by dividebysandwich** [comment]
Oops sorry! I've updated the binary to have terminal output.
The reason why you don't see it is in the first line of main.rs, which disables the terminal window appearing on windows. I have added a conditional so this is only used on windows.

Unfortunately there doesn't seem to be a good way to not have a new console window pop up on windows when using the program with a shortcut, while also retaining console output when running it from the console. I saw some hacks to close the console window after it is created but that seems weird.

So anyway, should work okay on windows and linux, except for there being no console output on windows if you run it from the terminal. If you want that, remove the windows_subsystem stanza in main.rs.

**Comment by 70sh1** [comment]
I get it now. In fact, I had never run a program through explorer before, only through terminal.

My bad. I had completely forgotten that windows programs don't usually output anything to the console unless they start a new terminal window. Thanks for the explanation!
