### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by dividebysandwich** [dividebysandwich/LightningView#3]
There is currently no support for animated GIFs. The libraries support pulling out the frames from a gif file, but I do not know if they do composition correctly (you may need to overlay multiple frames to get the current frame bitmap)

Might be neccessary to use a separate crate like https://crates.io/crates/gif ...

The rendering needs to use the correct timing and replace the displayed image with the current frame.

**Comment by dividebysandwich** [comment]
Implemented!

**Comment by BugFixesAndPerformanceImprovements** [comment]
Animated GIFs don't appear to work as of LightningView version 2.5.2 on Linux (elementaryOS 8.1 (Ubuntu-based)). Tested with both the .deb and .flatpak releases.

Also tested the same GIF with [Emulsion](https://github.com/ArturKovacs/emulsion) and [qView](https://github.com/jurplel/qView) and they open it just fine.

Tested with this GIF for what it's worth: https://tenor.com/en-us/view/lightning-storm-gif-8622540

**Comment by dividebysandwich** [comment]
@BugFixesAndPerformanceImprovements Thanks, fixed in v2.5.3!
