### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Shooodax** [dividebysandwich/LightningView#9]
i need help i have irfan viewer and i want the mouse zoom in options but i dont know how to implement this into irfan viewer so can  someone help me please?

**Comment by dividebysandwich** [comment]
According to the irfanview forums:
_If "View other files in directory" is disabled in Settings, Browsing/Editing the scrollwheel will now zoom in and out without the use of the Ctrl key modifier._ 

This was one of the reasons LightningView was developed in the first place.

**Comment by Shooodax** [comment]
yeah i know that u can do that but u cant really view the other files so i just wanna implement this entire thing into irfanview

**Comment by dividebysandwich** [comment]
That's not how this works unfortunately. If there's functionality missing that you would like to see in LightningView, please let me know. I can't fix Irfanview, sorry.
